name: github_actions_gtest_example-Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Build and install GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake -DCMAKE_CXX_STANDARD=17 .
        sudo make
        sudo cp lib/*.a /usr/lib/
        sudo cp lib/*.a /usr/local/lib/

    - name: Verify gtest installation
      run: ls -l /usr/lib/libgtest*

    - uses: actions/checkout@v2  # 更新为最新的 v2 版本

    - name: Configure CMake
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: Build project
      run: cd build && make && ls -l

    - name: Run Tests
      run: |
        cd build
        # 查找所有测试可执行文件并运行它们，生成 XML 报告
        find . -type f -executable -name "*Test" -exec {} --gtest_output=xml:{}_report.xml \;

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v3  # 更新为最新的 v3 版本
      with:
        name: test-reports
        path: build/*_report.xml
